using System.Collections.Generic;

namespace JJ.Framework.Data
{
    public interface IRepository<TEntity, in TID>
    {
        TEntity TryGet(TID id);
        TEntity Get(TID id);
        TEntity Create();
        void Delete(TEntity entity);
        void Update(TEntity entity);
        void Insert(TEntity entity);

        /// <summary>
        /// Sends pending statements to the data store but does not yet commit the transaction.
        /// This may fill in data generated by the data store, such as ID's.
        /// </summary>
        void Flush();
        void Commit();
        void Rollback();
    }
}
