//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Runtime Version:4.0.30319.42000
//
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JJ.Framework.Validation.Resources {
	using System;
	
	
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class ValidationResources {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal ValidationResources() {
		}
		
		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JJ.Framework.Validation.Resources.ValidationResources", typeof(ValidationResources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to {0} are empty..
		/// </summary>
		internal static string AreEmpty_WithName {
			get {
				return ResourceManager.GetString("AreEmpty_WithName", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to {0} contains {1}..
		/// </summary>
		internal static string Contains_WithName_AndValue {
			get {
				return ResourceManager.GetString("Contains_WithName_AndValue", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to {0} should not exist..
		/// </summary>
		internal static string Exists_WithName {
			get {
				return ResourceManager.GetString("Exists_WithName", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to File &apos;{0}&apos; already exists..
		/// </summary>
		internal static string FileAlreadyExists_WithFilePath {
			get {
				return ResourceManager.GetString("FileAlreadyExists_WithFilePath", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to File &apos;{0}&apos; not found..
		/// </summary>
		internal static string FileNotFound_WithFilePath {
			get {
				return ResourceManager.GetString("FileNotFound_WithFilePath", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Folder &apos;{0}&apos; already exists..
		/// </summary>
		internal static string FolderAlreadyExists_WithFolderPAth {
			get {
				return ResourceManager.GetString("FolderAlreadyExists_WithFolderPAth", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Folder &apos;{0}&apos; not found..
		/// </summary>
		internal static string FolderNotFound_WithFolderPath {
			get {
				return ResourceManager.GetString("FolderNotFound_WithFolderPath", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to {0} is above {1}..
		/// </summary>
		internal static string GreaterThan_WithName_AndLimit {
			get {
				return ResourceManager.GetString("GreaterThan_WithName_AndLimit", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to {0} should be less than {1}..
		/// </summary>
		internal static string GreaterThanOrEqual_WithName_AndLimit {
			get {
				return ResourceManager.GetString("GreaterThanOrEqual_WithName_AndLimit", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to {0} has empty values..
		/// </summary>
		internal static string HasNulls_WithName {
			get {
				return ResourceManager.GetString("HasNulls_WithName", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to {0} is invalid..
		/// </summary>
		internal static string Invalid_WithName {
			get {
				return ResourceManager.GetString("Invalid_WithName", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to {0} is an invalid choice..
		/// </summary>
		internal static string InvalidChoice_WithName {
			get {
				return ResourceManager.GetString("InvalidChoice_WithName", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to {0} has an invalid number..
		/// </summary>
		internal static string InvalidIndex_WithName {
			get {
				return ResourceManager.GetString("InvalidIndex_WithName", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to {0} is a broken number..
		/// </summary>
		internal static string IsBrokenNumber_WithName {
			get {
				return ResourceManager.GetString("IsBrokenNumber_WithName", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to {0} is empty..
		/// </summary>
		internal static string IsEmpty_WithName {
			get {
				return ResourceManager.GetString("IsEmpty_WithName", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to {0} is {1}..
		/// </summary>
		internal static string IsEqual_WithName_AndValue {
			get {
				return ResourceManager.GetString("IsEqual_WithName_AndValue", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to {0} should not be filled in..
		/// </summary>
		internal static string IsFilledIn_WithName {
			get {
				return ResourceManager.GetString("IsFilledIn_WithName", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to {0} is infinite..
		/// </summary>
		internal static string IsInfinity_WithName {
			get {
				return ResourceManager.GetString("IsInfinity_WithName", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to {0} is in the list of disallowed values..
		/// </summary>
		internal static string IsInList_WithName {
			get {
				return ResourceManager.GetString("IsInList_WithName", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to {0} is not an integer number..
		/// </summary>
		internal static string IsInteger_WithName {
			get {
				return ResourceManager.GetString("IsInteger_WithName", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to {0} is not a number..
		/// </summary>
		internal static string IsNaN_WithName {
			get {
				return ResourceManager.GetString("IsNaN_WithName", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to {0} is of type {1}..
		/// </summary>
		internal static string IsOfType_WithName_AndTypeName {
			get {
				return ResourceManager.GetString("IsOfType_WithName_AndTypeName", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to {0} is zero..
		/// </summary>
		internal static string IsZero_WithName {
			get {
				return ResourceManager.GetString("IsZero_WithName", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to {0} is longer than {1} characters..
		/// </summary>
		internal static string LengthExceeded_WithName_AndLength {
			get {
				return ResourceManager.GetString("LengthExceeded_WithName_AndLength", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to {0} is below {1}..
		/// </summary>
		internal static string LessThan_WithName_AndLimit {
			get {
				return ResourceManager.GetString("LessThan_WithName_AndLimit", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to {0} should be more than {1}..
		/// </summary>
		internal static string LessThanOrEqual_WithName_AndLimit {
			get {
				return ResourceManager.GetString("LessThanOrEqual_WithName_AndLimit", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to {0} or {1} can be filled in, but not both at the same time..
		/// </summary>
		internal static string NotBoth_WithTwoNames {
			get {
				return ResourceManager.GetString("NotBoth_WithTwoNames", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to {0} is not a broken number..
		/// </summary>
		internal static string NotBrokenNumber_WithName {
			get {
				return ResourceManager.GetString("NotBrokenNumber_WithName", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to {0} does not contain {1}..
		/// </summary>
		internal static string NotContains_WithName_AndValue {
			get {
				return ResourceManager.GetString("NotContains_WithName_AndValue", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to {0} are not empty..
		/// </summary>
		internal static string NotEmpty_WithName_Plural {
			get {
				return ResourceManager.GetString("NotEmpty_WithName_Plural", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to {0} is not empty..
		/// </summary>
		internal static string NotEmpty_WithName_Singular {
			get {
				return ResourceManager.GetString("NotEmpty_WithName_Singular", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to {0} is not {1}..
		/// </summary>
		internal static string NotEqual_WithName_AndValue {
			get {
				return ResourceManager.GetString("NotEqual_WithName_AndValue", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to {0} does not exist..
		/// </summary>
		internal static string NotExists_WithName {
			get {
				return ResourceManager.GetString("NotExists_WithName", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to {0} {1} does not exist..
		/// </summary>
		internal static string NotExists_WithName_AndValue {
			get {
				return ResourceManager.GetString("NotExists_WithName_AndValue", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Not filled in..
		/// </summary>
		internal static string NotFilledIn {
			get {
				return ResourceManager.GetString("NotFilledIn", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to {0} is not filled in..
		/// </summary>
		internal static string NotFilledIn_WithName {
			get {
				return ResourceManager.GetString("NotFilledIn_WithName", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to {0} is not one of the allowed items..
		/// </summary>
		internal static string NotInList_WithName {
			get {
				return ResourceManager.GetString("NotInList_WithName", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to {0} should have one of the values: {1}..
		/// </summary>
		internal static string NotInList_WithName_AndAllowedValues {
			get {
				return ResourceManager.GetString("NotInList_WithName_AndAllowedValues", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to {0} {1} is not one of the allowed items..
		/// </summary>
		internal static string NotInList_WithName_AndValue {
			get {
				return ResourceManager.GetString("NotInList_WithName_AndValue", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to {0} {1} not allowed. Allowed items: {2}..
		/// </summary>
		internal static string NotInList_WithName_AndValue_AndAllowedValues {
			get {
				return ResourceManager.GetString("NotInList_WithName_AndValue_AndAllowedValues", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to {0} is not an integer number..
		/// </summary>
		internal static string NotInteger_WithName {
			get {
				return ResourceManager.GetString("NotInteger_WithName", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to {0} is not of type {1}..
		/// </summary>
		internal static string NotOfType_WithName_AndTypeName {
			get {
				return ResourceManager.GetString("NotOfType_WithName_AndTypeName", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to {0} are not unique. Duplicates: {1}..
		/// </summary>
		internal static string NotUnique_WithName_AndDuplicateValues_Plural {
			get {
				return ResourceManager.GetString("NotUnique_WithName_AndDuplicateValues_Plural", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to {0} is not unique. Duplicates: {1}..
		/// </summary>
		internal static string NotUnique_WithName_AndDuplicateValues_Singular {
			get {
				return ResourceManager.GetString("NotUnique_WithName_AndDuplicateValues_Singular", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to {0} {1} is not unique..
		/// </summary>
		internal static string NotUnique_WithName_AndValue_Singular {
			get {
				return ResourceManager.GetString("NotUnique_WithName_AndValue_Singular", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to {0} are not unique..
		/// </summary>
		internal static string NotUnique_WithName_Plural {
			get {
				return ResourceManager.GetString("NotUnique_WithName_Plural", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to {0} is not unique..
		/// </summary>
		internal static string NotUnique_WithName_Singular {
			get {
				return ResourceManager.GetString("NotUnique_WithName_Singular", resourceCulture);
			}
		}
	}
}
