//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JJ.Presentation.SetText.WinForms.Online.GeneratedServiceClient.SetTextAppService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SetTextViewModel", Namespace="http://schemas.datacontract.org/2004/07/JJ.Presentation.SetText.Interface.ViewModels")]
    [System.SerializableAttribute()]
    public partial class SetTextViewModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SyncSuccessfulMessageVisibleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TextWasSavedButNotYetSynchronizedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TextWasSavedMessageVisibleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private JJ.Presentation.SetText.WinForms.Online.GeneratedServiceClient.SetTextAppService.ValidationMessage[] ValidationMessagesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SyncSuccessfulMessageVisible {
            get {
                return this.SyncSuccessfulMessageVisibleField;
            }
            set {
                if ((this.SyncSuccessfulMessageVisibleField.Equals(value) != true)) {
                    this.SyncSuccessfulMessageVisibleField = value;
                    this.RaisePropertyChanged("SyncSuccessfulMessageVisible");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TextWasSavedButNotYetSynchronized {
            get {
                return this.TextWasSavedButNotYetSynchronizedField;
            }
            set {
                if ((this.TextWasSavedButNotYetSynchronizedField.Equals(value) != true)) {
                    this.TextWasSavedButNotYetSynchronizedField = value;
                    this.RaisePropertyChanged("TextWasSavedButNotYetSynchronized");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TextWasSavedMessageVisible {
            get {
                return this.TextWasSavedMessageVisibleField;
            }
            set {
                if ((this.TextWasSavedMessageVisibleField.Equals(value) != true)) {
                    this.TextWasSavedMessageVisibleField = value;
                    this.RaisePropertyChanged("TextWasSavedMessageVisible");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public JJ.Presentation.SetText.WinForms.Online.GeneratedServiceClient.SetTextAppService.ValidationMessage[] ValidationMessages {
            get {
                return this.ValidationMessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.ValidationMessagesField, value) != true)) {
                    this.ValidationMessagesField = value;
                    this.RaisePropertyChanged("ValidationMessages");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidationMessage", Namespace="http://schemas.datacontract.org/2004/07/JJ.Business.CanonicalModel")]
    [System.SerializableAttribute()]
    public partial class ValidationMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PropertyKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PropertyKey {
            get {
                return this.PropertyKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.PropertyKeyField, value) != true)) {
                    this.PropertyKeyField = value;
                    this.RaisePropertyChanged("PropertyKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SetTextAppService.ISetTextAppService")]
    public interface ISetTextAppService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISetTextAppService/Show", ReplyAction="http://tempuri.org/ISetTextAppService/ShowResponse")]
        JJ.Presentation.SetText.WinForms.Online.GeneratedServiceClient.SetTextAppService.SetTextViewModel Show(string cultureName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISetTextAppService/Show", ReplyAction="http://tempuri.org/ISetTextAppService/ShowResponse")]
        System.Threading.Tasks.Task<JJ.Presentation.SetText.WinForms.Online.GeneratedServiceClient.SetTextAppService.SetTextViewModel> ShowAsync(string cultureName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISetTextAppService/Save", ReplyAction="http://tempuri.org/ISetTextAppService/SaveResponse")]
        JJ.Presentation.SetText.WinForms.Online.GeneratedServiceClient.SetTextAppService.SetTextViewModel Save(JJ.Presentation.SetText.WinForms.Online.GeneratedServiceClient.SetTextAppService.SetTextViewModel viewModel, string cultureName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISetTextAppService/Save", ReplyAction="http://tempuri.org/ISetTextAppService/SaveResponse")]
        System.Threading.Tasks.Task<JJ.Presentation.SetText.WinForms.Online.GeneratedServiceClient.SetTextAppService.SetTextViewModel> SaveAsync(JJ.Presentation.SetText.WinForms.Online.GeneratedServiceClient.SetTextAppService.SetTextViewModel viewModel, string cultureName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISetTextAppServiceChannel : JJ.Presentation.SetText.WinForms.Online.GeneratedServiceClient.SetTextAppService.ISetTextAppService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SetTextAppServiceClient : System.ServiceModel.ClientBase<JJ.Presentation.SetText.WinForms.Online.GeneratedServiceClient.SetTextAppService.ISetTextAppService>, JJ.Presentation.SetText.WinForms.Online.GeneratedServiceClient.SetTextAppService.ISetTextAppService {
        
        public SetTextAppServiceClient() {
        }
        
        public SetTextAppServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SetTextAppServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SetTextAppServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SetTextAppServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public JJ.Presentation.SetText.WinForms.Online.GeneratedServiceClient.SetTextAppService.SetTextViewModel Show(string cultureName) {
            return base.Channel.Show(cultureName);
        }
        
        public System.Threading.Tasks.Task<JJ.Presentation.SetText.WinForms.Online.GeneratedServiceClient.SetTextAppService.SetTextViewModel> ShowAsync(string cultureName) {
            return base.Channel.ShowAsync(cultureName);
        }
        
        public JJ.Presentation.SetText.WinForms.Online.GeneratedServiceClient.SetTextAppService.SetTextViewModel Save(JJ.Presentation.SetText.WinForms.Online.GeneratedServiceClient.SetTextAppService.SetTextViewModel viewModel, string cultureName) {
            return base.Channel.Save(viewModel, cultureName);
        }
        
        public System.Threading.Tasks.Task<JJ.Presentation.SetText.WinForms.Online.GeneratedServiceClient.SetTextAppService.SetTextViewModel> SaveAsync(JJ.Presentation.SetText.WinForms.Online.GeneratedServiceClient.SetTextAppService.SetTextViewModel viewModel, string cultureName) {
            return base.Channel.SaveAsync(viewModel, cultureName);
        }
    }
}
