using System;
using System.Reflection;
using System.Runtime.CompilerServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: CLSCompliantAttribute(false)]
[assembly: AssemblyTitleAttribute("NHibernate.ByteCode.LinFu.Tests")]
[assembly: AssemblyDescriptionAttribute("The Unit Tests for LinFu ByteCode.")]
[assembly: AssemblyCompanyAttribute("NHibernate.org")]
[assembly: AssemblyProductAttribute("NHibernate.ByteCode.LinFu.Tests")]
[assembly: AssemblyCopyrightAttribute("Licensed under LGPL.")]
[assembly: AssemblyVersionAttribute("1.0.0.1")]
[assembly: AssemblyInformationalVersionAttribute("1.0")]
[assembly: AssemblyFileVersionAttribute("3.1.0.4000")]
[assembly: AssemblyDelaySignAttribute(false)]

