//------------------------------------------------------------------------------
// <auto-generated>
//     Deze code is gegenereerd met een hulpprogramma.
//     Runtime-versie:2.0.50727.5477
//
//     Als u wijzigingen aanbrengt in dit bestand, kan dit onjuist gedrag veroorzaken wanneer
//     de code wordt gegenereerd.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IResourceService")]
public interface IResourceService {
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResourceService/GetMessages", ReplyAction="http://tempuri.org/IResourceService/GetMessagesResponse")]
    JJ.Apps.SetText.AppService.Models.Messages GetMessages(string cultureName);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResourceService/GetLabels", ReplyAction="http://tempuri.org/IResourceService/GetLabelsResponse")]
    JJ.Apps.SetText.AppService.Models.Labels GetLabels(string cultureName);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResourceService/GetTitles", ReplyAction="http://tempuri.org/IResourceService/GetTitlesResponse")]
    JJ.Apps.SetText.AppService.Models.Titles GetTitles(string cultureName);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IResourceServiceChannel : IResourceService, System.ServiceModel.IClientChannel {
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class ResourceServiceClient : System.ServiceModel.ClientBase<IResourceService>, IResourceService {
    
    public ResourceServiceClient() {
    }
    
    public ResourceServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName) {
    }
    
    public ResourceServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress) {
    }
    
    public ResourceServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress) {
    }
    
    public ResourceServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress) {
    }
    
    public JJ.Apps.SetText.AppService.Models.Messages GetMessages(string cultureName) {
        return base.Channel.GetMessages(cultureName);
    }
    
    public JJ.Apps.SetText.AppService.Models.Labels GetLabels(string cultureName) {
        return base.Channel.GetLabels(cultureName);
    }
    
    public JJ.Apps.SetText.AppService.Models.Titles GetTitles(string cultureName) {
        return base.Channel.GetTitles(cultureName);
    }
}
namespace JJ.Apps.SetText.AppService.Models {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Messages", Namespace="http://schemas.datacontract.org/2004/07/JJ.Apps.SetText.AppService.Models")]
    public partial class Messages : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string SavedField;
        
        private string ServiceUnavailableField;
        
        private string SynchronizationPendingField;
        
        private string SynchronizedWithServerField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Saved {
            get {
                return this.SavedField;
            }
            set {
                this.SavedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceUnavailable {
            get {
                return this.ServiceUnavailableField;
            }
            set {
                this.ServiceUnavailableField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SynchronizationPending {
            get {
                return this.SynchronizationPendingField;
            }
            set {
                this.SynchronizationPendingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SynchronizedWithServer {
            get {
                return this.SynchronizedWithServerField;
            }
            set {
                this.SynchronizedWithServerField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Labels", Namespace="http://schemas.datacontract.org/2004/07/JJ.Apps.SetText.AppService.Models")]
    public partial class Labels : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string TextField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                this.TextField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Titles", Namespace="http://schemas.datacontract.org/2004/07/JJ.Apps.SetText.AppService.Models")]
    public partial class Titles : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string GoOfflineField;
        
        private string GoOnlineField;
        
        private string SetTextField;
        
        private string SynchronizeField;
        
        private string TryAgainField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GoOffline {
            get {
                return this.GoOfflineField;
            }
            set {
                this.GoOfflineField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GoOnline {
            get {
                return this.GoOnlineField;
            }
            set {
                this.GoOnlineField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SetText {
            get {
                return this.SetTextField;
            }
            set {
                this.SetTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Synchronize {
            get {
                return this.SynchronizeField;
            }
            set {
                this.SynchronizeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TryAgain {
            get {
                return this.TryAgainField;
            }
            set {
                this.TryAgainField = value;
            }
        }
    }
}

