//------------------------------------------------------------------------------
// <auto-generated>
//     Deze code is gegenereerd met een hulpprogramma.
//     Runtime-versie:2.0.50727.5477
//
//     Als u wijzigingen aanbrengt in dit bestand, kan dit onjuist gedrag veroorzaken wanneer
//     de code wordt gegenereerd.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by Web Services Description Language Utility
//Mono Framework v2.0.50727.5477
//


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IResourceService", Namespace="http://tempuri.org/")]
public partial class ResourceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback GetMessagesOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetLabelsOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetTitlesOperationCompleted;
    
    /// <remarks/>
    public ResourceService() {
        this.Url = "http://localhost:6371/ResourceService.svc";
    }
    
    /// <remarks/>
    public event GetMessagesCompletedEventHandler GetMessagesCompleted;
    
    /// <remarks/>
    public event GetLabelsCompletedEventHandler GetLabelsCompleted;
    
    /// <remarks/>
    public event GetTitlesCompletedEventHandler GetTitlesCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IResourceService/GetMessages", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public Messages GetMessages([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string cultureName) {
        object[] results = this.Invoke("GetMessages", new object[] {
                    cultureName});
        return ((Messages)(results[0]));
    }
    
    /// <remarks/>
    public void GetMessagesAsync(string cultureName) {
        this.GetMessagesAsync(cultureName, null);
    }
    
    /// <remarks/>
    public void GetMessagesAsync(string cultureName, object userState) {
        if ((this.GetMessagesOperationCompleted == null)) {
            this.GetMessagesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMessagesOperationCompleted);
        }
        this.InvokeAsync("GetMessages", new object[] {
                    cultureName}, this.GetMessagesOperationCompleted, userState);
    }
    
    private void OnGetMessagesOperationCompleted(object arg) {
        if ((this.GetMessagesCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetMessagesCompleted(this, new GetMessagesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IResourceService/GetLabels", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public Labels GetLabels([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string cultureName) {
        object[] results = this.Invoke("GetLabels", new object[] {
                    cultureName});
        return ((Labels)(results[0]));
    }
    
    /// <remarks/>
    public void GetLabelsAsync(string cultureName) {
        this.GetLabelsAsync(cultureName, null);
    }
    
    /// <remarks/>
    public void GetLabelsAsync(string cultureName, object userState) {
        if ((this.GetLabelsOperationCompleted == null)) {
            this.GetLabelsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLabelsOperationCompleted);
        }
        this.InvokeAsync("GetLabels", new object[] {
                    cultureName}, this.GetLabelsOperationCompleted, userState);
    }
    
    private void OnGetLabelsOperationCompleted(object arg) {
        if ((this.GetLabelsCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetLabelsCompleted(this, new GetLabelsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IResourceService/GetTitles", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public Titles GetTitles([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string cultureName) {
        object[] results = this.Invoke("GetTitles", new object[] {
                    cultureName});
        return ((Titles)(results[0]));
    }
    
    /// <remarks/>
    public void GetTitlesAsync(string cultureName) {
        this.GetTitlesAsync(cultureName, null);
    }
    
    /// <remarks/>
    public void GetTitlesAsync(string cultureName, object userState) {
        if ((this.GetTitlesOperationCompleted == null)) {
            this.GetTitlesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTitlesOperationCompleted);
        }
        this.InvokeAsync("GetTitles", new object[] {
                    cultureName}, this.GetTitlesOperationCompleted, userState);
    }
    
    private void OnGetTitlesOperationCompleted(object arg) {
        if ((this.GetTitlesCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetTitlesCompleted(this, new GetTitlesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <opmerkingen/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/JJ.Apps.SetText.AppService.Models")]
public partial class Messages {
    
    private string savedField;
    
    private string serviceUnavailableField;
    
    private string synchronizationPendingField;
    
    private string synchronizedWithServerField;
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Saved {
        get {
            return this.savedField;
        }
        set {
            this.savedField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ServiceUnavailable {
        get {
            return this.serviceUnavailableField;
        }
        set {
            this.serviceUnavailableField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string SynchronizationPending {
        get {
            return this.synchronizationPendingField;
        }
        set {
            this.synchronizationPendingField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string SynchronizedWithServer {
        get {
            return this.synchronizedWithServerField;
        }
        set {
            this.synchronizedWithServerField = value;
        }
    }
}

/// <opmerkingen/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/JJ.Apps.SetText.AppService.Models")]
public partial class Titles {
    
    private string goOfflineField;
    
    private string goOnlineField;
    
    private string setTextField;
    
    private string synchronizeField;
    
    private string tryAgainField;
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string GoOffline {
        get {
            return this.goOfflineField;
        }
        set {
            this.goOfflineField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string GoOnline {
        get {
            return this.goOnlineField;
        }
        set {
            this.goOnlineField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string SetText {
        get {
            return this.setTextField;
        }
        set {
            this.setTextField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Synchronize {
        get {
            return this.synchronizeField;
        }
        set {
            this.synchronizeField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string TryAgain {
        get {
            return this.tryAgainField;
        }
        set {
            this.tryAgainField = value;
        }
    }
}

/// <opmerkingen/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/JJ.Apps.SetText.AppService.Models")]
public partial class Labels {
    
    private string textField;
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
public delegate void GetMessagesCompletedEventHandler(object sender, GetMessagesCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetMessagesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetMessagesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public Messages Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((Messages)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
public delegate void GetLabelsCompletedEventHandler(object sender, GetLabelsCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetLabelsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetLabelsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public Labels Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((Labels)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
public delegate void GetTitlesCompletedEventHandler(object sender, GetTitlesCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetTitlesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetTitlesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public Titles Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((Titles)(this.results[0]));
        }
    }
}
