//------------------------------------------------------------------------------
// <auto-generated>
//     Deze code is gegenereerd met een hulpprogramma.
//     Runtime-versie:2.0.50727.5477
//
//     Als u wijzigingen aanbrengt in dit bestand, kan dit onjuist gedrag veroorzaken wanneer
//     de code wordt gegenereerd.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ISetTextAppService")]
public interface ISetTextAppService {
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISetTextAppService/Show", ReplyAction="http://tempuri.org/ISetTextAppService/ShowResponse")]
    JJ.Apps.SetText.ViewModels.SetTextViewModel Show();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISetTextAppService/Save", ReplyAction="http://tempuri.org/ISetTextAppService/SaveResponse")]
    JJ.Apps.SetText.ViewModels.SetTextViewModel Save(JJ.Apps.SetText.ViewModels.SetTextViewModel viewModel);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface ISetTextAppServiceChannel : ISetTextAppService, System.ServiceModel.IClientChannel {
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class SetTextAppServiceClient : System.ServiceModel.ClientBase<ISetTextAppService>, ISetTextAppService {
    
    public SetTextAppServiceClient() {
    }
    
    public SetTextAppServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName) {
    }
    
    public SetTextAppServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress) {
    }
    
    public SetTextAppServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress) {
    }
    
    public SetTextAppServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress) {
    }
    
    public JJ.Apps.SetText.ViewModels.SetTextViewModel Show() {
        return base.Channel.Show();
    }
    
    public JJ.Apps.SetText.ViewModels.SetTextViewModel Save(JJ.Apps.SetText.ViewModels.SetTextViewModel viewModel) {
        return base.Channel.Save(viewModel);
    }
}
namespace JJ.Apps.SetText.ViewModels {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SetTextViewModel", Namespace="http://schemas.datacontract.org/2004/07/JJ.Apps.SetText.ViewModels")]
    public partial class SetTextViewModel : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool SyncSuccessfulMessageVisibleField;
        
        private string TextField;
        
        private bool TextWasSavedButNotYetSynchronizedField;
        
        private bool TextWasSavedMessageVisibleField;
        
        private IList<JJ.Models.Canonical.ValidationMessage> ValidationMessagesField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SyncSuccessfulMessageVisible {
            get {
                return this.SyncSuccessfulMessageVisibleField;
            }
            set {
                this.SyncSuccessfulMessageVisibleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                this.TextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TextWasSavedButNotYetSynchronized {
            get {
                return this.TextWasSavedButNotYetSynchronizedField;
            }
            set {
                this.TextWasSavedButNotYetSynchronizedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TextWasSavedMessageVisible {
            get {
                return this.TextWasSavedMessageVisibleField;
            }
            set {
                this.TextWasSavedMessageVisibleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IList<JJ.Models.Canonical.ValidationMessage> ValidationMessages {
            get {
                return this.ValidationMessagesField;
            }
            set {
                this.ValidationMessagesField = value;
            }
        }
    }
}
namespace JJ.Models.Canonical {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidationMessage", Namespace="http://schemas.datacontract.org/2004/07/JJ.Models.Canonical")]
    public partial class ValidationMessage : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string PropertyKeyField;
        
        private string TextField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PropertyKey {
            get {
                return this.PropertyKeyField;
            }
            set {
                this.PropertyKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                this.TextField = value;
            }
        }
    }
}

