//------------------------------------------------------------------------------
// <auto-generated>
//     Deze code is gegenereerd met een hulpprogramma.
//     Runtime-versie:2.0.50727.5477
//
//     Als u wijzigingen aanbrengt in dit bestand, kan dit onjuist gedrag veroorzaken wanneer
//     de code wordt gegenereerd.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by Web Services Description Language Utility
//Mono Framework v2.0.50727.5477
//


[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_ISetTextAppService", Namespace="http://tempuri.org/")]
public partial class SetTextAppService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback ShowOperationCompleted;
    
    private System.Threading.SendOrPostCallback SaveOperationCompleted;
    
    public SetTextAppService() {
        this.Url = "http://localhost:6371/SetTextAppService.svc";
    }
    
    public event ShowCompletedEventHandler ShowCompleted;
    
    public event SaveCompletedEventHandler SaveCompleted;
    
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISetTextAppService/Show", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: XmlElementAttribute(IsNullable=true)]
    public SetTextViewModel Show() {
        object[] results = this.Invoke("Show", new object[0]);
        return ((SetTextViewModel)(results[0]));
    }
    
    public void ShowAsync() {
        this.ShowAsync(null);
    }
    
    public void ShowAsync(object userState) {
        if ((this.ShowOperationCompleted == null)) {
            this.ShowOperationCompleted = new System.Threading.SendOrPostCallback(this.OnShowOperationCompleted);
        }
        this.InvokeAsync("Show", new object[0], this.ShowOperationCompleted, userState);
    }
    
    private void OnShowOperationCompleted(object arg) {
        if ((this.ShowCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.ShowCompleted(this, new ShowCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISetTextAppService/Save", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: XmlElementAttribute(IsNullable=true)]
    public SetTextViewModel Save([XmlElementAttribute(IsNullable=true)] SetTextViewModel viewModel) {
        object[] results = this.Invoke("Save", new object[] {
                    viewModel});
        return ((SetTextViewModel)(results[0]));
    }
    
    public void SaveAsync(SetTextViewModel viewModel) {
        this.SaveAsync(viewModel, null);
    }
    
    public void SaveAsync(SetTextViewModel viewModel, object userState) {
        if ((this.SaveOperationCompleted == null)) {
            this.SaveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveOperationCompleted);
        }
        this.InvokeAsync("Save", new object[] {
                    viewModel}, this.SaveOperationCompleted, userState);
    }
    
    private void OnSaveOperationCompleted(object arg) {
        if ((this.SaveCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SaveCompleted(this, new SaveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/JJ.Apps.SetText.ViewModels")]
public partial class SetTextViewModel {
    
    private bool syncSuccessfulMessageVisibleField;
    
    private bool syncSuccessfulMessageVisibleFieldSpecified;
    
    private string textField;
    
    private bool textWasSavedButNotYetSynchronizedField;
    
    private bool textWasSavedButNotYetSynchronizedFieldSpecified;
    
    private bool textWasSavedMessageVisibleField;
    
    private bool textWasSavedMessageVisibleFieldSpecified;
    
    private ValidationMessage[] validationMessagesField;
    
    public bool SyncSuccessfulMessageVisible {
        get {
            return this.syncSuccessfulMessageVisibleField;
        }
        set {
            this.syncSuccessfulMessageVisibleField = value;
        }
    }
    
    [XmlIgnoreAttribute()]
    public bool SyncSuccessfulMessageVisibleSpecified {
        get {
            return this.syncSuccessfulMessageVisibleFieldSpecified;
        }
        set {
            this.syncSuccessfulMessageVisibleFieldSpecified = value;
        }
    }
    
    //[XmlElementAttribute(IsNullable=true)]
    public string Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
    
    public bool TextWasSavedButNotYetSynchronized {
        get {
            return this.textWasSavedButNotYetSynchronizedField;
        }
        set {
            this.textWasSavedButNotYetSynchronizedField = value;
        }
    }
    
    [XmlIgnoreAttribute()]
    public bool TextWasSavedButNotYetSynchronizedSpecified {
        get {
            return this.textWasSavedButNotYetSynchronizedFieldSpecified;
        }
        set {
            this.textWasSavedButNotYetSynchronizedFieldSpecified = value;
        }
    }
    
    public bool TextWasSavedMessageVisible {
        get {
            return this.textWasSavedMessageVisibleField;
        }
        set {
            this.textWasSavedMessageVisibleField = value;
        }
    }
    
    [XmlIgnoreAttribute()]
    public bool TextWasSavedMessageVisibleSpecified {
        get {
            return this.textWasSavedMessageVisibleFieldSpecified;
        }
        set {
            this.textWasSavedMessageVisibleFieldSpecified = value;
        }
    }
    
    //[XmlArrayAttribute(IsNullable=true)]
    [XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/JJ.Models.Canonical")]
    public ValidationMessage[] ValidationMessages {
        get {
            return this.validationMessagesField;
        }
        set {
            this.validationMessagesField = value;
        }
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/JJ.Models.Canonical")]
public partial class ValidationMessage {
    
    private string propertyKeyField;
    
    private string textField;
    
    //[XmlElementAttribute(IsNullable=true)]
    public string PropertyKey {
        get {
            return this.propertyKeyField;
        }
        set {
            this.propertyKeyField = value;
        }
    }
    
    //[XmlElementAttribute(IsNullable=true)]
    public string Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
public delegate void ShowCompletedEventHandler(object sender, ShowCompletedEventArgs e);

[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ShowCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal ShowCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    public SetTextViewModel Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((SetTextViewModel)(this.results[0]));
        }
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
public delegate void SaveCompletedEventHandler(object sender, SaveCompletedEventArgs e);

[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class SaveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal SaveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public SetTextViewModel Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((SetTextViewModel)(this.results[0]));
        }
    }
}
