//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JJ.Presentation.SetText.WinForms.Online.GeneratedServiceClient.ResourceAppService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Messages", Namespace="http://schemas.datacontract.org/2004/07/JJ.Presentation.SetText.AppService.Interface.Mode" +
        "ls")]
    [System.SerializableAttribute()]
    public partial class Messages : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SavedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceUnavailableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SynchronizationPendingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SynchronizedWithServerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Saved {
            get {
                return this.SavedField;
            }
            set {
                if ((object.ReferenceEquals(this.SavedField, value) != true)) {
                    this.SavedField = value;
                    this.RaisePropertyChanged("Saved");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceUnavailable {
            get {
                return this.ServiceUnavailableField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceUnavailableField, value) != true)) {
                    this.ServiceUnavailableField = value;
                    this.RaisePropertyChanged("ServiceUnavailable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SynchronizationPending {
            get {
                return this.SynchronizationPendingField;
            }
            set {
                if ((object.ReferenceEquals(this.SynchronizationPendingField, value) != true)) {
                    this.SynchronizationPendingField = value;
                    this.RaisePropertyChanged("SynchronizationPending");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SynchronizedWithServer {
            get {
                return this.SynchronizedWithServerField;
            }
            set {
                if ((object.ReferenceEquals(this.SynchronizedWithServerField, value) != true)) {
                    this.SynchronizedWithServerField = value;
                    this.RaisePropertyChanged("SynchronizedWithServer");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Labels", Namespace="http://schemas.datacontract.org/2004/07/JJ.Presentation.SetText.AppService.Interface.Mode" +
        "ls")]
    [System.SerializableAttribute()]
    public partial class Labels : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Titles", Namespace="http://schemas.datacontract.org/2004/07/JJ.Presentation.SetText.AppService.Interface.Mode" +
        "ls")]
    [System.SerializableAttribute()]
    public partial class Titles : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GoOfflineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GoOnlineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SetTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SynchronizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TryAgainField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GoOffline {
            get {
                return this.GoOfflineField;
            }
            set {
                if ((object.ReferenceEquals(this.GoOfflineField, value) != true)) {
                    this.GoOfflineField = value;
                    this.RaisePropertyChanged("GoOffline");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GoOnline {
            get {
                return this.GoOnlineField;
            }
            set {
                if ((object.ReferenceEquals(this.GoOnlineField, value) != true)) {
                    this.GoOnlineField = value;
                    this.RaisePropertyChanged("GoOnline");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SetText {
            get {
                return this.SetTextField;
            }
            set {
                if ((object.ReferenceEquals(this.SetTextField, value) != true)) {
                    this.SetTextField = value;
                    this.RaisePropertyChanged("SetText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Synchronize {
            get {
                return this.SynchronizeField;
            }
            set {
                if ((object.ReferenceEquals(this.SynchronizeField, value) != true)) {
                    this.SynchronizeField = value;
                    this.RaisePropertyChanged("Synchronize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TryAgain {
            get {
                return this.TryAgainField;
            }
            set {
                if ((object.ReferenceEquals(this.TryAgainField, value) != true)) {
                    this.TryAgainField = value;
                    this.RaisePropertyChanged("TryAgain");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ResourceAppService.IResourceAppService")]
    public interface IResourceAppService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResourceAppService/GetMessages", ReplyAction="http://tempuri.org/IResourceAppService/GetMessagesResponse")]
        JJ.Presentation.SetText.WinForms.Online.GeneratedServiceClient.ResourceAppService.Messages GetMessages(string cultureName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResourceAppService/GetMessages", ReplyAction="http://tempuri.org/IResourceAppService/GetMessagesResponse")]
        System.Threading.Tasks.Task<JJ.Presentation.SetText.WinForms.Online.GeneratedServiceClient.ResourceAppService.Messages> GetMessagesAsync(string cultureName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResourceAppService/GetLabels", ReplyAction="http://tempuri.org/IResourceAppService/GetLabelsResponse")]
        JJ.Presentation.SetText.WinForms.Online.GeneratedServiceClient.ResourceAppService.Labels GetLabels(string cultureName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResourceAppService/GetLabels", ReplyAction="http://tempuri.org/IResourceAppService/GetLabelsResponse")]
        System.Threading.Tasks.Task<JJ.Presentation.SetText.WinForms.Online.GeneratedServiceClient.ResourceAppService.Labels> GetLabelsAsync(string cultureName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResourceAppService/GetTitles", ReplyAction="http://tempuri.org/IResourceAppService/GetTitlesResponse")]
        JJ.Presentation.SetText.WinForms.Online.GeneratedServiceClient.ResourceAppService.Titles GetTitles(string cultureName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResourceAppService/GetTitles", ReplyAction="http://tempuri.org/IResourceAppService/GetTitlesResponse")]
        System.Threading.Tasks.Task<JJ.Presentation.SetText.WinForms.Online.GeneratedServiceClient.ResourceAppService.Titles> GetTitlesAsync(string cultureName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IResourceAppServiceChannel : JJ.Presentation.SetText.WinForms.Online.GeneratedServiceClient.ResourceAppService.IResourceAppService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ResourceAppServiceClient : System.ServiceModel.ClientBase<JJ.Presentation.SetText.WinForms.Online.GeneratedServiceClient.ResourceAppService.IResourceAppService>, JJ.Presentation.SetText.WinForms.Online.GeneratedServiceClient.ResourceAppService.IResourceAppService {
        
        public ResourceAppServiceClient() {
        }
        
        public ResourceAppServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ResourceAppServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ResourceAppServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ResourceAppServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public JJ.Presentation.SetText.WinForms.Online.GeneratedServiceClient.ResourceAppService.Messages GetMessages(string cultureName) {
            return base.Channel.GetMessages(cultureName);
        }
        
        public System.Threading.Tasks.Task<JJ.Presentation.SetText.WinForms.Online.GeneratedServiceClient.ResourceAppService.Messages> GetMessagesAsync(string cultureName) {
            return base.Channel.GetMessagesAsync(cultureName);
        }
        
        public JJ.Presentation.SetText.WinForms.Online.GeneratedServiceClient.ResourceAppService.Labels GetLabels(string cultureName) {
            return base.Channel.GetLabels(cultureName);
        }
        
        public System.Threading.Tasks.Task<JJ.Presentation.SetText.WinForms.Online.GeneratedServiceClient.ResourceAppService.Labels> GetLabelsAsync(string cultureName) {
            return base.Channel.GetLabelsAsync(cultureName);
        }
        
        public JJ.Presentation.SetText.WinForms.Online.GeneratedServiceClient.ResourceAppService.Titles GetTitles(string cultureName) {
            return base.Channel.GetTitles(cultureName);
        }
        
        public System.Threading.Tasks.Task<JJ.Presentation.SetText.WinForms.Online.GeneratedServiceClient.ResourceAppService.Titles> GetTitlesAsync(string cultureName) {
            return base.Channel.GetTitlesAsync(cultureName);
        }
    }
}
