using System;
using System.Reflection;
using System.Runtime.CompilerServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: CLSCompliantAttribute(true)]
[assembly: AssemblyTitleAttribute("NHibernate.TestDatabaseSetup")]
[assembly: AssemblyDescriptionAttribute("Test Database Setup for NHibernate.")]
[assembly: AssemblyCompanyAttribute("NHibernate.org")]
[assembly: AssemblyProductAttribute("NHibernate.TestDatabaseSetup")]
[assembly: AssemblyCopyrightAttribute("Licensed under LGPL.")]
[assembly: AssemblyVersionAttribute("3.3.1.4000")]
[assembly: AssemblyInformationalVersionAttribute("3.3.1.4000")]
[assembly: AssemblyFileVersionAttribute("3.3.1.4000")]
[assembly: AssemblyDelaySignAttribute(false)]

